DOC_AGENTS_COUNT = 15
POLICE_AGENTS_COUNT = 10
BIOMETRIC_AGENTS_COUNT = 12

DOCS_VERIFICATION_MIN_DURATION = 5
DOCS_VERIFICATION_MAX_DURATION = 15

POLICE_VERIFICATION_MIN_DURATION = 3
POLICE_VERIFICATION_MAX_DURATION = 8

BIOMETRIC_VERIFICATION_MIN_DURATION = 5
BIOMETRIC_VERIFICATION_MAX_DURATION = 7

APPLICANTS_COUNT = 180

SIMULATION_DURATION = 60 # in seconds
SIMULATION_COUNT = 2